org.gradle.daemon=false
org.gradle.debug=false

minecraft_release=26.1
minecraft_version=26.1
minecraft_version_range=[26.1,)
neoforge_version=26.1.1.2-beta
neoforge_version_range=[26.1.1.2-beta,)
loader_version_range=[1,)

mod_id=glodium
mod_name=Glodium
mod_license=MIT
mod_version=26.1-1.0-neoforge
mod_group_id=com.glodblock.github.glodium
mod_authors=GlodBlock
mod_description=Codelib

mavenCentralPublishing=true
signAllPublications=true